image: archlinux
oauth: pages.sr.ht/PAGES:RW
environment:
  site: the-empire.systems
packages:
  - rubygems
sources:
  - https://git.sr.ht/~heywoodlh/the-empire.systems
tasks:
  - setup: |
      sudo gem install --bindir=/usr/local/bin/ jekyll -v 3.8.6
      sudo gem install --bindir=/usr/local/bin/ bundler
      sudo gem install --bindir=/usr/local/bin/ jekyll-font-awesome-sass
      gem install github-pages
  - package: |
      cd $site
      ./build.sh
      tar -C _site -czvf site.tar.gz .
  - upload: |
      cd $site
      acurl -f https://pages.sr.ht/publish/$site -f https://pages.sr.ht/publish/www.$site -Fcontent=@site.tar.gz
triggers:
  - action: email
    condition: failure
    to: heywoodlh@tyrannyofthesun.com
